<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: globaldata/globaldata.proto

namespace Globaldata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>globaldata.AllCountryResponse</code>
 */
class AllCountryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string statuscode = 1;</code>
     */
    protected $statuscode = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated .globaldata.AllCountryList result = 3;</code>
     */
    private $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $statuscode
     *     @type string $description
     *     @type array<\Globaldata\AllCountryList>|\Google\Protobuf\Internal\RepeatedField $result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Globaldata\Globaldata::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string statuscode = 1;</code>
     * @return string
     */
    public function getStatuscode()
    {
        return $this->statuscode;
    }

    /**
     * Generated from protobuf field <code>string statuscode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatuscode($var)
    {
        GPBUtil::checkString($var, True);
        $this->statuscode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .globaldata.AllCountryList result = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>repeated .globaldata.AllCountryList result = 3;</code>
     * @param array<\Globaldata\AllCountryList>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResult($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Globaldata\AllCountryList::class);
        $this->result = $arr;

        return $this;
    }

}

