<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: globaldata/globaldata.proto

namespace Globaldata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>globaldata.EmptyRequest</code>
 */
class EmptyRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Globaldata\Globaldata::initOnce();
        parent::__construct($data);
    }

}

