<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rootadminweb/rootadminweb.proto

namespace GPBMetadata\Rootadminweb;

class Rootadminweb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
î
rootadminweb/rootadminweb.protorootadminweb"
EmptyRequest"1
DoLoginRequest
email (	
password (	"ê
DoLoginList

id (	
roleid (	
email (	
phone (	
	firstname (	
lastname (	
fullname (	
clientid (	"v
DoLoginResponse

statuscode (	
description (	
session (	)
result (2.rootadminweb.DoLoginList" 
DoLogoutRequest
email (	";
DoLogoutResponse

statuscode (	
description (	2®
RootAdminWebServiceF
DoLogin.rootadminweb.DoLoginRequest.rootadminweb.DoLoginResponseI
DoLogout.rootadminweb.DoLogoutRequest.rootadminweb.DoLogoutResponseBZ.bproto3'
        , true);

        static::$is_initialized = true;
    }
}

