<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rootadminweb/rootadminweb.proto

namespace Rootadminweb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rootadminweb.DoLoginList</code>
 */
class DoLoginList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string roleid = 2;</code>
     */
    protected $roleid = '';
    /**
     * Generated from protobuf field <code>string email = 3;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string phone = 4;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string firstname = 5;</code>
     */
    protected $firstname = '';
    /**
     * Generated from protobuf field <code>string lastname = 6;</code>
     */
    protected $lastname = '';
    /**
     * Generated from protobuf field <code>string fullname = 7;</code>
     */
    protected $fullname = '';
    /**
     * Generated from protobuf field <code>string clientid = 8;</code>
     */
    protected $clientid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $roleid
     *     @type string $email
     *     @type string $phone
     *     @type string $firstname
     *     @type string $lastname
     *     @type string $fullname
     *     @type string $clientid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rootadminweb\Rootadminweb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string roleid = 2;</code>
     * @return string
     */
    public function getRoleid()
    {
        return $this->roleid;
    }

    /**
     * Generated from protobuf field <code>string roleid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleid($var)
    {
        GPBUtil::checkString($var, True);
        $this->roleid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 4;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string firstname = 5;</code>
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Generated from protobuf field <code>string firstname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstname($var)
    {
        GPBUtil::checkString($var, True);
        $this->firstname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lastname = 6;</code>
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Generated from protobuf field <code>string lastname = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLastname($var)
    {
        GPBUtil::checkString($var, True);
        $this->lastname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fullname = 7;</code>
     * @return string
     */
    public function getFullname()
    {
        return $this->fullname;
    }

    /**
     * Generated from protobuf field <code>string fullname = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFullname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fullname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string clientid = 8;</code>
     * @return string
     */
    public function getClientid()
    {
        return $this->clientid;
    }

    /**
     * Generated from protobuf field <code>string clientid = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientid($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientid = $var;

        return $this;
    }

}

