<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/test.proto

namespace Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>test.EmptyRequest</code>
 */
class EmptyRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Test\Test::initOnce();
        parent::__construct($data);
    }

}

