<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/test.proto

namespace Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>test.HelloWorldResponse</code>
 */
class HelloWorldResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string hello = 1;</code>
     */
    protected $hello = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hello
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Test\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string hello = 1;</code>
     * @return string
     */
    public function getHello()
    {
        return $this->hello;
    }

    /**
     * Generated from protobuf field <code>string hello = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHello($var)
    {
        GPBUtil::checkString($var, True);
        $this->hello = $var;

        return $this;
    }

}

